# MIT License
# 
# Copyright (c) 2023 Juan Medina
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Web

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Web
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Checkout original repo
        uses: actions/checkout@v3
        with:
          repository: juan-medina/twitch-rat
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wasm
        run: make wasm

      - name: Archive build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-directory
          path: build/web        

      - name: Clone blog repo
        uses: actions/checkout@v3
        with:
          repository: juan-medina/blog
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifact      
        uses: actions/download-artifact@v4
        with:
          name: build-directory
          path: build-directory

      - name: Copy wasm to blog repo
        run: |
          rm -rf blog/docs/twitch-rat
          mkdir -p blog/docs/twitch-rat
          cp -r build-directory/* blog/docs/twitch-rat
          rm -rf build-directory

      - name: Commit files
        run: |
          git config --local user.email "jamedina@gmail.com"
          git config --local user.name "Juan Medina"
          git commit -a -m "Twitch Rat Release v${{ github.event.release.tag_name }}"

      - name: Push to blog repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: juan-medina/blog
          branch: main
          directory: blog
