# MIT License
# 
# Copyright (c) 2023 Juan Medina
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Web

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: juan-medina/twitch-rat
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wasm
        run: make wasm

      - name: Make zip & MD5 with the wasm project with the tag number
        run: |
          cd build/web
          zip -r "${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip" *
          md5sum "${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip" > "${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip.md5"

      - name: Add zip to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "build/web/${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip"
          asset_name: "${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip"
          tag: ${{ github.ref }}
          overwrite: true

      - name: Add zip MD5 to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "build/web/${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip.md5"
          asset_name: "${{ github.event.repository.name }}-${{ github.event.release.name }}-web.zip.md5"
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
